---
- name: Syslog to log to central log server
  become: true
  become_user: root
  template:
    src: rsyslog-elks.conf.j2
    dest: /etc/rsyslog.d/60-logging-elks.conf
    mode: 0644
    owner: 0
    group: 0
  notify: restart rsyslog
